name: machine_test
description: "A new Flutter project."


publish_to: 'none' 

version: 1.0.0+1

environment:
  sdk: '>=3.3.0 <4.0.0'


dependencies:
  flutter:
    sdk: flutter 
  
  cupertino_icons: ^1.0.6



  mobx: ^2.2.0
  flutter_mobx: ^2.1.0
  mobx_codegen: ^2.4.0

  
  http: ^1.1.0
  retry: ^3.1.2
  http_interceptor: ^2.0.0-beta.7

  
  freezed_annotation: ^2.4.1
  json_annotation: ^4.8.1
  get_it: ^7.2.0
  dartz: ^0.10.1
  injectable: ^2.1.0
  flutter_screenutil: ^5.8.4



  shared_preferences: ^2.2.2
  flutter_secure_storage: ^9.0.0
  fluttertoast: ^8.2.4
  google_fonts: ^6.1.0
  cached_network_image: ^3.3.1
  svg_flutter: ^0.0.1
  carousel_slider: ^4.2.1
  animations: ^2.0.8





dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0
  freezed: ^2.4.2
  build_runner: ^2.4.6
  json_serializable: ^6.7.1
  auto_route_generator: ^7.3.1
  injectable_generator: ^2.1.4





flutter:

  
  
  
  uses-material-design: true
  assets: 
  - assets/
  - assets/svg/
  - assets/images/

  
  
  
  

  
  

  
  

  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
